// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://tnopzbxlfzweiqrmwbww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRub3B6YnhsZnp3ZWlxcm13Ynd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUwMzgwNzMsImV4cCI6MjA4MDYxNDA3M30.CjtRgiqFBSgN9qV2HGhj2bUN1-c3d1PkN1arA44dHgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);